// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4-uavoH7XH1ikUCvVrucWqe14cOs8mcc',
    appId: '1:1046811389890:web:d31426eba5476fec2df05b',
    messagingSenderId: '1046811389890',
    projectId: 'flash-chat-3b5bd',
    authDomain: 'flash-chat-3b5bd.firebaseapp.com',
    storageBucket: 'flash-chat-3b5bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhtgQynUtL2U64uUZm14acX8sU5460WEk',
    appId: '1:1046811389890:android:d3f11eecddbcaa2b2df05b',
    messagingSenderId: '1046811389890',
    projectId: 'flash-chat-3b5bd',
    storageBucket: 'flash-chat-3b5bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEHRzSSDCx62KeuSBgOD3p5Jbd66SyjVk',
    appId: '1:1046811389890:ios:174c96a3fcb8f3f52df05b',
    messagingSenderId: '1046811389890',
    projectId: 'flash-chat-3b5bd',
    storageBucket: 'flash-chat-3b5bd.appspot.com',
    iosClientId: '1046811389890-5rv4riuidc5id1f6lnrvui88e72gde16.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEHRzSSDCx62KeuSBgOD3p5Jbd66SyjVk',
    appId: '1:1046811389890:ios:174c96a3fcb8f3f52df05b',
    messagingSenderId: '1046811389890',
    projectId: 'flash-chat-3b5bd',
    storageBucket: 'flash-chat-3b5bd.appspot.com',
    iosClientId: '1046811389890-5rv4riuidc5id1f6lnrvui88e72gde16.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );
}
